path_to_dataset: '../../datasets/REM_data'
numShuffles: 1000
L: 150 # 5s @ 30fps
K: 2
numNeurons: 128
maxIters: 50
Lambda: 0.0001
speed_threshold: 5
samplingFrequency: 30
train_test_ratio: .5
path_to_output: '../../output_REM'