# I/O paths
path_to_output: "../../output_REM"
path_to_dataset: "../../datasets/REM_data"

# Params
numShuffles: 1000
speed_threshold: 9
sampling_frequency: 30
train_test_ratio: .5
seed: 42 # Seed for reproducibility
z_threshold: 2
numNeurons: 256
overwrite_mode: "always" # Set as 'always' or 'never'
event_overlap_window: 30 # in frames

# Tuning curves
spatialBinSize: 2.5 # cm
equalize_sampling: True

# SeqNMF
L: 100 # sequence length in frames
K: 2
maxIters: 50
Lambda: 0.0001
expansionFactor: 1.0
lambda_OrthW: 0 # 1 enforces event-bases sequences.
lambda_L1W: 0
shift: True

# Bayesian decoding
stepSize: 5 #step_size (in frames)
windowSize: 15 # Time window (in frames)
filtWindowSize: 0 # Time window for Bayesian temporal filtering. 0 for no filtering

