# I/O paths
path_to_output: '../../output_REM'
path_to_dataset: '../../datasets/REM_data'

# Parameters
numShuffles: 1000
L: 150 # 5s @ 30fps
K: 2
maxIters: 50
Lambda: 0.0001

speed_threshold: 5
sampling_frequency: 30
train_test_ratio: .5
seed: 42
z_threshold: 2
numNeurons: 128
spatialBinSize: 2.5 # cm

overwrite_mode: 'always' # Set as 'always' or 'never'