# I/O paths
path_to_output: '../../output_REM'
path_to_dataset: '../../datasets/REM_data'

# Params
numShuffles: 1000
speed_threshold: 9
sampling_frequency: 30
train_test_ratio: .5
seed: 42 # Seed for reproducibility
z_threshold: 2
numNeurons: 256
spatialBinSize: 2.5 # cm
overwrite_mode: 'always' # Set as 'always' or 'never'

# SeqNMF
L: 100 # sequence length in frames
K: 2
maxIters: 50
Lambda: 0.0001
expansionFactor: 1.0

# Bayesian decoding
stepSize: 50 #step_size (in frames)
windowSize: 100 # Time window (in frames)

