# I/O paths
path_to_output: '../../output_REM'
path_to_dataset: '../../datasets/REM_data'

# SeqNMF
L: 100 # 5s @ 30fps
K: 2
maxIters: 50
Lambda: 0.0001
expansionFactor: 1.0

# Bayesian decoding
stepSize: 5 #step_size (in frames)
windowSize: 14 # TIme window (in frames)

# Misc
numShuffles: 1000
speed_threshold: 9
sampling_frequency: 30
train_test_ratio: .5
seed: 42
z_threshold: 2
numNeurons: 128
spatialBinSize: 2.5 # cm

overwrite_mode: 'always' # Set as 'always' or 'never'